### ISSUE TITLE
On screen keyboard appears on start, need to close it every time.

### ISSUE THREAD

**Issue by LordJABA** [RadRussianRus/sddm-slice#6]
Not sure if that's what supposed to happen. I have 2 monitors, maybe relevant.
Anyway to just get rid of the keyboard for good? I will newer use it...

**Comment by LordJABA** [comment]
Dirty workaround - turn it off completely by adding `InputMethod=` in `[General]` section in `/etc/sddm.conf`. 
But it should be bound to a button not open on start and every time I click text input field

**Comment by khipukamayuq** [comment]
@LordJABA thanks for the work around. Ran into this same issue after just installing yesterday. @RadRussianRus  Fwiw I experienced this solely using my laptop w/o any external monitor.

**Comment by oversword** [comment]
I'm getting this too, same fix worked, I only have one monitor though.
I've been looking through the code, nothing in there suggests it's intentional.
I think perhaps it has something to do with the fact it's seeing the screen as a tablet?
The real question is, why doesn't it happen on other themes? Is there a common fix in use?

**Comment by RadRussianRus** [comment]
That's kinda strange. I haven't seen anything specific in other themes about this and haven't catched this bug myself.

**Comment by RadRussianRus** [comment]
I've catched this bug in my laptop. But it also happens on default theme, so it could be an SDDM problem. If it could be fixed on my side, I'll fix it, of course, but it's probably on SDDM side.

**Comment by RadRussianRus** [comment]
Found out that it works fine in SDDM Breeze theme. So it will be adapted in this theme too.

**Comment by RadRussianRus** [comment]
I've disabled virtual keyboard for now. But I'm planning to adapt it to this theme in future versions.
