### ISSUE TITLE
Incorrect GH link

### ISSUE THREAD

**Issue by the0neWhoKnocks** [RadRussianRus/sddm-slice#8]
The link for this theme points to a nonexistent repo.

Wrong link `slice-sddm` instead of `sddm-slice`: https://github.com/RadRussianRus/sddm-slice/blob/1ddbc490a500bdd938a797e72a480f535191b45e/metadata.desktop#L9

**Comment by RadRussianRus** [comment]
Thanks, fixed in https://github.com/RadRussianRus/sddm-slice/commit/763b8f4e01c00c1f8590fc7a103e14f6e8449443.
